//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Sputnik.Interop.ParserEngine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceClass {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceClass() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Sputnik.Interop.ParserEngine.ResourceClass", typeof(ResourceClass).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BasicNegativePrereqInputTemplate.
        /// </summary>
        internal static string BasicNegativePrereqTemplate_FileName {
            get {
                return ResourceManager.GetString("BasicNegativePrereqTemplate_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BasicNegativeInputTemplate.
        /// </summary>
        internal static string BasicNegativeTemplate_FileName {
            get {
                return ResourceManager.GetString("BasicNegativeTemplate_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BasicPrereqInputTemplate.
        /// </summary>
        internal static string BasicPrereqTemplate_FileName {
            get {
                return ResourceManager.GetString("BasicPrereqTemplate_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BasicInputTemplate.
        /// </summary>
        internal static string BasicTemplate_FileName {
            get {
                return ResourceManager.GetString("BasicTemplate_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChecksRegex.
        /// </summary>
        internal static string ChecksRegexSettingKey {
            get {
                return ResourceManager.GetString("ChecksRegexSettingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommentsRegex.
        /// </summary>
        internal static string CommentsRegexSettingKey {
            get {
                return ResourceManager.GetString("CommentsRegexSettingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has been converted and saved at: {0}.
        /// </summary>
        internal static string FileConverted_Log {
            get {
                return ResourceManager.GetString("FileConverted_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalCodeRegex.
        /// </summary>
        internal static string GlobalCodeRegexKey {
            get {
                return ResourceManager.GetString("GlobalCodeRegexKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputXMLPath.
        /// </summary>
        internal static string InputXMLPath {
            get {
                return ResourceManager.GetString("InputXMLPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed with exception, Message : {0}.
        /// </summary>
        internal static string IOException {
            get {
                return ResourceManager.GetString("IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogFileDirectory.
        /// </summary>
        internal static string LogFileDirectorySettingKey {
            get {
                return ResourceManager.GetString("LogFileDirectorySettingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assertion.
        /// </summary>
        internal static string LookFor_Assertion {
            get {
                return ResourceManager.GetString("LookFor_Assertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        internal static string LookFor_Description {
            get {
                return ResourceManager.GetString("LookFor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string LookFor_Name {
            get {
                return ResourceManager.GetString("LookFor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to negative.
        /// </summary>
        internal static string LookFor_Negative {
            get {
                return ResourceManager.GetString("LookFor_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strict_mode_negative.
        /// </summary>
        internal static string LookFor_NegativeStrictMode {
            get {
                return ResourceManager.GetString("LookFor_NegativeStrictMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to section.
        /// </summary>
        internal static string LookFor_Section {
            get {
                return ResourceManager.GetString("LookFor_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching regex is found for the file: {0}.
        /// </summary>
        internal static string Match_RegEx_Found {
            get {
                return ResourceManager.GetString("Match_RegEx_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any matching regex format for the file: {0}.
        /// </summary>
        internal static string NoMatch_RegEex {
            get {
                return ResourceManager.GetString("NoMatch_RegEex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press enter key to exit....
        /// </summary>
        internal static string PressExit {
            get {
                return ResourceManager.GetString("PressExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expression used for the file: {0} is {1} and its seqence Id is {2}.
        /// </summary>
        internal static string RegEx_Used {
            get {
                return ResourceManager.GetString("RegEx_Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of sputnik test case files before conversion: {0}.
        /// </summary>
        internal static string Total_Input_Files {
            get {
                return ResourceManager.GetString("Total_Input_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of test cases which actually got converted: {0}.
        /// </summary>
        internal static string Total_Output_Files {
            get {
                return ResourceManager.GetString("Total_Output_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occured while converting files:.
        /// </summary>
        internal static string Unexpected_Error {
            get {
                return ResourceManager.GetString("Unexpected_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while reading regex formats from InputFormats.xml files: {0}.
        /// </summary>
        internal static string XMLException_Log {
            get {
                return ResourceManager.GetString("XMLException_Log", resourceCulture);
            }
        }
    }
}
