// Test generated by: property-test-generator

/*---
esid: sec-number.prototype
description: Property test for Number.prototype
info: |
  Number.prototype
  - The initial value of `Number.prototype` is the Number prototype object.
  - This property has the attributes { [[Writable]]: false, [[Enumerable]]:
    false, [[Configurable]]: false }.

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [propertyHelper.js]
---*/

verifyPrimordialProperty(Number, "prototype", {
  writable: false,
  enumerable: false,
  configurable: false,
});
