// Test generated by: property-test-generator

/*---
esid: sec-properties-of-the-number-prototype-object
description: Property test for Number.prototype
info: |
  Properties of the Number Prototype Object
  - is %Number.prototype%.
  - is an ordinary object.
  - is itself a Number object; it has a [[NumberData]] internal slot with the
    value +0𝔽.
  - has a [[Prototype]] internal slot whose value is %Object.prototype%.

  Unless specified otherwise, the [[Extensible]] internal slot of a built-in object
  initially has the value true.

  Unless otherwise specified every built-in prototype object has the Object prototype
  object, which is the initial value of the expression Object.prototype (20.1.3),
  as the value of its [[Prototype]] internal slot, except the Object prototype object
  itself.
flags: [generated]
---*/

assert.sameValue(Object.getPrototypeOf(Number.prototype), Object.prototype);
assert.sameValue(Object.isExtensible(Number.prototype), true);
assert.sameValue(typeof Number.prototype, "object");
