// Test generated by: property-test-generator

/*---
esid: sec-uint8array.prototype.tohex
description: Property test for Uint8Array.prototype.toHex
info: |
  Uint8Array.prototype.toHex ( )

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [builtin.js, propertyHelper.js]
features: [Proxy, Reflect, Reflect.construct, TypedArray, uint8array-base64]
---*/

verifyBuiltinFunction(Uint8Array.prototype.toHex, "toHex", 0);

verifyPrimordialProperty(Uint8Array.prototype, "toHex", {
  value: Uint8Array.prototype.toHex,
  writable: true,
  enumerable: false,
  configurable: true,
});
