// Test generated by: property-test-generator

/*---
esid: sec-number.prototype.toexponential
description: Property test for Number.prototype.toExponential
info: |
  Number.prototype.toExponential ( fractionDigits )
  - This method returns a String containing this Number value represented in
    decimal exponential notation with one digit before the significand's
    decimal point and fractionDigits digits after the significand's decimal
    point. If fractionDigits is undefined, it includes as many significand
    digits as necessary to uniquely specify the Number (just like in ToString
    except that in this case the Number is always output in exponential
    notation).

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [builtin.js, propertyHelper.js]
features: [Proxy, Reflect, Reflect.construct]
---*/

verifyBuiltinFunction(Number.prototype.toExponential, "toExponential", 1);

verifyPrimordialProperty(Number.prototype, "toExponential", {
  value: Number.prototype.toExponential,
  writable: true,
  enumerable: false,
  configurable: true,
});
