// Test generated by: property-test-generator

/*---
esid: sec-number.prototype.toprecision
description: Property test for Number.prototype.toPrecision
info: |
  Number.prototype.toPrecision ( precision )
  - This method returns a String containing this Number value represented either
    in decimal exponential notation with one digit before the significand's
    decimal point and precision - 1 digits after the significand's decimal
    point or in decimal fixed notation with precision significant digits. If
    precision is undefined, it calls ToString instead.

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [builtin.js, propertyHelper.js]
features: [Proxy, Reflect, Reflect.construct]
---*/

verifyBuiltinFunction(Number.prototype.toPrecision, "toPrecision", 1);

verifyPrimordialProperty(Number.prototype, "toPrecision", {
  value: Number.prototype.toPrecision,
  writable: true,
  enumerable: false,
  configurable: true,
});
