// Test generated by: property-test-generator

/*---
esid: sec-number.prototype.valueof
description: Property test for Number.prototype.valueOf
info: |
  Number.prototype.valueOf ( )

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [builtin.js, propertyHelper.js]
features: [Proxy, Reflect, Reflect.construct]
---*/

verifyBuiltinFunction(Number.prototype.valueOf, "valueOf", 0);

verifyPrimordialProperty(Number.prototype, "valueOf", {
  value: Number.prototype.valueOf,
  writable: true,
  enumerable: false,
  configurable: true,
});
