// Test generated by: property-test-generator

/*---
esid: sec-number-constructor
description: Property test for Number
info: |
  The Number Constructor

    Number ( value )

    Properties of the Number Constructor
    - has a [[Prototype]] internal slot whose value is %Function.prototype%.
flags: [generated]
includes: [builtin.js, propertyHelper.js]
features: [Proxy, Reflect, Reflect.construct]
---*/

verifyBuiltinConstructor(Number, "Number", 1, Function.prototype);
