// Test generated by: property-test-generator

/*---
esid: sec-constructor-properties-of-the-global-object-number
description: Property test for Number
info: |
  Number ( . . . )

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [propertyHelper.js]
---*/

verifyPrimordialProperty(this, "Number", {
  value: Number,
  writable: true,
  enumerable: false,
  configurable: true,
});
