// Copyright 2017 Mathias Bynens. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.

/*---
author: Mathias Bynens
description: >
  Unicode property escapes for `Prepended_Concatenation_Mark`
info: |
  Generated by https://github.com/mathiasbynens/unicode-property-escapes-tests
  Unicode v9.0.0
esid: sec-static-semantics-unicodematchproperty-p
features: [regexp-unicode-property-escapes]
includes: [regExpUtils.js]
---*/

const matchSymbols = buildString({
  loneCodePoints: [
    0x0006DD,
    0x00070F,
    0x0008E2,
    0x0110BD
  ],
  ranges: [
    [0x000600, 0x000605]
  ]
});
testPropertyEscapes(
  /^\p{Prepended_Concatenation_Mark}+$/u,
  matchSymbols,
  "\\p{Prepended_Concatenation_Mark}"
);
testPropertyEscapes(
  /^\p{PCM}+$/u,
  matchSymbols,
  "\\p{PCM}"
);

const nonMatchSymbols = buildString({
  loneCodePoints: [],
  ranges: [
    [0x00DC00, 0x00DFFF],
    [0x000000, 0x0005FF],
    [0x000606, 0x0006DC],
    [0x0006DE, 0x00070E],
    [0x000710, 0x0008E1],
    [0x0008E3, 0x00DBFF],
    [0x00E000, 0x0110BC],
    [0x0110BE, 0x10FFFF]
  ]
});
testPropertyEscapes(
  /^\P{Prepended_Concatenation_Mark}+$/u,
  nonMatchSymbols,
  "\\P{Prepended_Concatenation_Mark}"
);
testPropertyEscapes(
  /^\P{PCM}+$/u,
  nonMatchSymbols,
  "\\P{PCM}"
);
