// Test generated by: property-test-generator

/*---
esid: sec-number.nan
description: Property test for Number.NaN
info: |
  Number.NaN
  - The value of `Number.NaN` is NaN.
  - This property has the attributes { [[Writable]]: false, [[Enumerable]]:
    false, [[Configurable]]: false }.

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [propertyHelper.js]
---*/

verifyPrimordialProperty(Number, "NaN", {
  value: 0/0,
  writable: false,
  enumerable: false,
  configurable: false,
});
