// Test generated by: property-test-generator

/*---
esid: sec-number.min_safe_integer
description: Property test for Number.MIN_SAFE_INTEGER
info: |
  Number.MIN_SAFE_INTEGER
  - The value of `Number.MIN_SAFE_INTEGER` is -9007199254740991𝔽 (𝔽(-(253 -
    1))).
  - This property has the attributes { [[Writable]]: false, [[Enumerable]]:
    false, [[Configurable]]: false }.

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [propertyHelper.js]
---*/

verifyPrimordialProperty(Number, "MIN_SAFE_INTEGER", {
  value: -9007199254740991,
  writable: false,
  enumerable: false,
  configurable: false,
});
