// Test generated by: property-test-generator

/*---
esid: sec-number.prototype.tolocalestring
description: Property test for Number.prototype.toLocaleString
info: |
  Number.prototype.toLocaleString ( [ reserved1 [ , reserved2 ] ] )
  - This method produces a String value that represents this Number value
    formatted according to the conventions of the host environment's current
    locale. This method is implementation-defined, and it is permissible, but
    not encouraged, for it to return the same thing as `toString`.
  - The meanings of the optional parameters to this method are defined in the
    ECMA-402 specification; implementations that do not include ECMA-402
    support must not use those parameter positions for anything else.

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [builtin.js, propertyHelper.js]
features: [Proxy, Reflect, Reflect.construct]
---*/

verifyBuiltinFunction(Number.prototype.toLocaleString, "toLocaleString", 0);

verifyPrimordialProperty(Number.prototype, "toLocaleString", {
  value: Number.prototype.toLocaleString,
  writable: true,
  enumerable: false,
  configurable: true,
});
