// Test generated by: property-test-generator

/*---
esid: sec-number.prototype.tofixed
description: Property test for Number.prototype.toFixed
info: |
  Number.prototype.toFixed ( fractionDigits )

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [builtin.js, propertyHelper.js]
features: [Proxy, Reflect, Reflect.construct]
---*/

verifyBuiltinFunction(Number.prototype.toFixed, "toFixed", 1);

verifyPrimordialProperty(Number.prototype, "toFixed", {
  value: Number.prototype.toFixed,
  writable: true,
  enumerable: false,
  configurable: true,
});
