// Test generated by: property-test-generator

/*---
esid: sec-uint8array.prototype.setfromhex
description: Property test for Uint8Array.prototype.setFromHex
info: |
  Uint8Array.prototype.setFromHex ( string )

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [builtin.js, propertyHelper.js]
features: [Proxy, Reflect, Reflect.construct, TypedArray, uint8array-base64]
---*/

verifyBuiltinFunction(Uint8Array.prototype.setFromHex, "setFromHex", 1);

verifyPrimordialProperty(Uint8Array.prototype, "setFromHex", {
  value: Uint8Array.prototype.setFromHex,
  writable: true,
  enumerable: false,
  configurable: true,
});
