// Test generated by: property-test-generator

/*---
esid: sec-number.isfinite
description: Property test for Number.isFinite
info: |
  Number.isFinite ( number )

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [builtin.js, propertyHelper.js]
features: [Proxy, Reflect, Reflect.construct]
---*/

verifyBuiltinFunction(Number.isFinite, "isFinite", 1);

verifyPrimordialProperty(Number, "isFinite", {
  value: Number.isFinite,
  writable: true,
  enumerable: false,
  configurable: true,
});
