// Test generated by: property-test-generator

/*---
esid: sec-number.parseint
description: Property test for Number.parseInt
info: |
  Number.parseInt ( string, radix )
  - The initial value of the "parseInt" property is %parseInt%.

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [propertyHelper.js]
---*/

assert.sameValue(Number.parseInt, parseInt);

verifyPrimordialProperty(Number, "parseInt", {
  value: parseInt,
  writable: true,
  enumerable: false,
  configurable: true,
});
