// Test generated by: property-test-generator

/*---
esid: sec-uint8array.prototype.tobase64
description: Property test for Uint8Array.prototype.toBase64
info: |
  Uint8Array.prototype.toBase64 ( [ options ] )

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [builtin.js, propertyHelper.js]
features: [Proxy, Reflect, Reflect.construct, TypedArray, uint8array-base64]
---*/

verifyBuiltinFunction(Uint8Array.prototype.toBase64, "toBase64", 0);

verifyPrimordialProperty(Uint8Array.prototype, "toBase64", {
  value: Uint8Array.prototype.toBase64,
  writable: true,
  enumerable: false,
  configurable: true,
});
