// Test generated by: property-test-generator

/*---
esid: sec-uint8array.fromhex
description: Property test for Uint8Array.fromHex
info: |
  Uint8Array.fromHex ( string )

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [builtin.js, propertyHelper.js]
features: [Proxy, Reflect, Reflect.construct, TypedArray, uint8array-base64]
---*/

verifyBuiltinFunction(Uint8Array.fromHex, "fromHex", 1);

verifyPrimordialProperty(Uint8Array, "fromHex", {
  value: Uint8Array.fromHex,
  writable: true,
  enumerable: false,
  configurable: true,
});
