// Test generated by: property-test-generator

/*---
esid: sec-number.min_value
description: Property test for Number.MIN_VALUE
info: |
  Number.MIN_VALUE
  - The value of `Number.MIN_VALUE` is the smallest positive value of the Number
    type, which is approximately 5 × 10-324.
  - In the IEEE 754-2019 double precision binary representation, the smallest
    possible value is a denormalized number. If an implementation does not
    support denormalized values, the value of `Number.MIN_VALUE` must be the
    smallest non-zero positive value that can actually be represented by the
    implementation.
  - This property has the attributes { [[Writable]]: false, [[Enumerable]]:
    false, [[Configurable]]: false }.

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [propertyHelper.js]
---*/

verifyPrimordialProperty(Number, "MIN_VALUE", {
  value: 5e-324,
  writable: false,
  enumerable: false,
  configurable: false,
});
