// Test generated by: property-test-generator

/*---
esid: sec-number.max_safe_integer
description: Property test for Number.MAX_SAFE_INTEGER
info: |
  Number.MAX_SAFE_INTEGER
  - The value of `Number.MAX_SAFE_INTEGER` is 9007199254740991𝔽 (𝔽(253 - 1)).
  - This property has the attributes { [[Writable]]: false, [[Enumerable]]:
    false, [[Configurable]]: false }.

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [propertyHelper.js]
---*/

verifyPrimordialProperty(Number, "MAX_SAFE_INTEGER", {
  value: 9007199254740991,
  writable: false,
  enumerable: false,
  configurable: false,
});
