// Test generated by: property-test-generator

/*---
esid: sec-number.isinteger
description: Property test for Number.isInteger
info: |
  Number.isInteger ( number )

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [builtin.js, propertyHelper.js]
features: [Proxy, Reflect, Reflect.construct]
---*/

verifyBuiltinFunction(Number.isInteger, "isInteger", 1);

verifyPrimordialProperty(Number, "isInteger", {
  value: Number.isInteger,
  writable: true,
  enumerable: false,
  configurable: true,
});
