// Test generated by: property-test-generator

/*---
esid: sup-number.prototype.tolocalestring
description: Property test for Number.prototype.toLocaleString
info: |
  Number.prototype.toLocaleString ( [ locales [ , options ] ] )
  - This definition supersedes the definition provided in ECMA-262, .

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [builtin.js, propertyHelper.js]
features: [Proxy, Reflect, Reflect.construct]
---*/

verifyBuiltinFunction(Number.prototype.toLocaleString, "toLocaleString", 0);

verifyPrimordialProperty(Number.prototype, "toLocaleString", {
  value: Number.prototype.toLocaleString,
  writable: true,
  enumerable: false,
  configurable: true,
});
