// Test generated by: property-test-generator

/*---
esid: sec-number.max_value
description: Property test for Number.MAX_VALUE
info: |
  Number.MAX_VALUE
  - The value of `Number.MAX_VALUE` is the largest positive finite value of the
    Number type, which is approximately 1.7976931348623157 × 10308.
  - This property has the attributes { [[Writable]]: false, [[Enumerable]]:
    false, [[Configurable]]: false }.

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [propertyHelper.js]
---*/

verifyPrimordialProperty(Number, "MAX_VALUE", {
  value: 1.7976931348623157e308,
  writable: false,
  enumerable: false,
  configurable: false,
});
