// Test generated by: property-test-generator

/*---
esid: sec-number.parsefloat
description: Property test for Number.parseFloat
info: |
  Number.parseFloat ( string )
  - The initial value of the "parseFloat" property is %parseFloat%.

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [propertyHelper.js]
---*/

assert.sameValue(Number.parseFloat, parseFloat);

verifyPrimordialProperty(Number, "parseFloat", {
  value: parseFloat,
  writable: true,
  enumerable: false,
  configurable: true,
});
