// Test generated by: property-test-generator

/*---
esid: sec-number.negative_infinity
description: Property test for Number.NEGATIVE_INFINITY
info: |
  Number.NEGATIVE_INFINITY
  - The value of `Number.NEGATIVE_INFINITY` is -∞𝔽.
  - This property has the attributes { [[Writable]]: false, [[Enumerable]]:
    false, [[Configurable]]: false }.

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [propertyHelper.js]
---*/

verifyPrimordialProperty(Number, "NEGATIVE_INFINITY", {
  value: -1/0,
  writable: false,
  enumerable: false,
  configurable: false,
});
