// Copyright 2026 Mathias Bynens. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.

/*---
author: Mathias Bynens
esid: sec-names-and-keywords
description: |
  Test that Unicode v7.0.0 ID_Continue characters are accepted as
  identifier part characters.
info: |
  Generated by https://github.com/mathiasbynens/caniunicode
---*/

var _ࣿఀಁഁ෦෧෨෩෪෫෬෭෮෯᪵᪶᪷᪸᪹᪺᪽᪰᪱᪲᪳᪴᪻᪼᳸᳹ᷧᷨᷩᷪᷫᷬᷭᷮᷯᷰᷱᷲᷳᷴ᷵ꧥ꧰꧱꧲꧳꧴꧵꧶꧷꧸꧹ꩼꩽ𑅳𑁿︧︨︩︪︫︬︭𐋠𐫦𐍶𐍷𐍸𐍹𐍺𐫥𑈬𑈭𑈮𑈯𑈰𑈱𑈲𑈳𑈴𑈶𑈵𑈷𑋟𑋠𑋡𑋢𑋣𑋤𑋥𑋦𑋧𑋨𑋩𑋪𑋰𑋱𑋲𑋳𑋴𑋵𑋶𑋷𑋸𑋹𑌁𑌂𑌃𑌼𑌾𑌿𑍀𑍁𑍂𑍃𑍄𑍇𑍈𑍋𑍌𑍍𑍗𑍢𑍣𑍦𑍧𑍨𑍩𑍪𑍫𑍬𑍰𑍱𑍲𑍳𑍴𑒰𑒱𑒲𑒳𑒴𑒵𑒶𑒷𑒸𑒻𑒻𑒼𑒽𑒾𑒿𑓀𑓁𑓃𑓂𑓐𑓑𑓒𑓓𑓔𑓕𑓖𑓗𑓘𑓙𑖯𑖰𑖱𑖲𑖳𑖴𑖵𑖸𑖹𑖺𑖻𑖼𑖽𑖾𑗀𑖿𑘰𑘱𑘲𑘳𑘴𑘵𑘶𑘷𑘸𑘹𑘺𑘻𑘼𑘽𑘾𑘿𑙀𑙐𑙑𑙒𑙓𑙔𑙕𑙖𑙗𑙘𑙙𑣠𑣡𑣢𑣣𑣤𑣥𑣦𑣧𑣨𑣩𖩠𖩡𖩢𖩣𖩤𖩥𖩦𖩧𖩨𖩩𖫰𖫱𖫲𖫳𖫴𖬰𖬱𖬲𖬳𖬴𖬵𖬶𖭐𖭑𖭒𖭓𖭔𖭕𖭖𖭗𖭘𖭙𛲝𛲞𞣐𞣑𞣒𞣓𞣔𞣕𞣖;
