// Test generated by: property-test-generator

/*---
esid: sec-number.epsilon
description: Property test for Number.EPSILON
info: |
  Number.EPSILON
  - The value of `Number.EPSILON` is the Number value for the magnitude of the
    difference between 1 and the smallest value greater than 1 that is
    representable as a Number value, which is approximately
    2.2204460492503130808472633361816 × 10-16.
  - This property has the attributes { [[Writable]]: false, [[Enumerable]]:
    false, [[Configurable]]: false }.

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [propertyHelper.js]
---*/

verifyPrimordialProperty(Number, "EPSILON", {
  value: 2.2204460492503130808472633361816e-16,
  writable: false,
  enumerable: false,
  configurable: false,
});
