// Test generated by: property-test-generator

/*---
esid: sec-uint8array.frombase64
description: Property test for Uint8Array.fromBase64
info: |
  Uint8Array.fromBase64 ( string [ , options ] )

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [builtin.js, propertyHelper.js]
features: [Proxy, Reflect, Reflect.construct, TypedArray, uint8array-base64]
---*/

verifyBuiltinFunction(Uint8Array.fromBase64, "fromBase64", 1);

verifyPrimordialProperty(Uint8Array, "fromBase64", {
  value: Uint8Array.fromBase64,
  writable: true,
  enumerable: false,
  configurable: true,
});
