// Test generated by: property-test-generator

/*---
esid: sec-number.prototype.tostring
description: Property test for Number.prototype.toString
info: |
  Number.prototype.toString ( [ radix ] )
  - This method is not generic; it throws a TypeError exception if its this
    value is not a Number or a Number object. Therefore, it cannot be
    transferred to other kinds of objects for use as a method.
  - The "length" property of this method is 1𝔽.

  ECMAScript Standard Built-in Objects

  Every other data property described in clauses 19 through 28 and in Annex B.2
  has the attributes { [[Writable]]: true, [[Enumerable]]: false,
  [[Configurable]]: true } unless otherwise specified.
flags: [generated]
includes: [builtin.js, propertyHelper.js]
features: [Proxy, Reflect, Reflect.construct]
---*/

verifyBuiltinFunction(Number.prototype.toString, "toString", 1);

verifyPrimordialProperty(Number.prototype, "toString", {
  value: Number.prototype.toString,
  writable: true,
  enumerable: false,
  configurable: true,
});
