name: Checks

on: push

jobs:
  lint:
    name: Lint tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/lint/requirements.txt

      - name: Test the lint tool
        run: ./tools/lint/test/run.py

      - name: Lint all tests
        run: ./tools/lint/lint.py test/
