name: Required PR checks

on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/lint/requirements.txt

      - name: Test the lint tool
        run: ./tools/lint/test/run.py

      - name: Identify new or changed tests
        id: changed_tests
        uses: tj-actions/changed-files@v45
        with:
          files: test/

      - name: Lint new or changed tests
        if: steps.changed_tests.outputs.any_changed == 'true'
        env:
          CHANGED: ${{ steps.changed_tests.outputs.all_changed_files }}
        run: |
          echo New or modified test files:
          for file in $CHANGED; do
            echo $file
          done
          ./tools/lint/lint.py $CHANGED
