name: Mirror "master" and "main" branches
on:
  push:
    branches:
      - master
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push
        run: |
          git push origin HEAD:master
          git push origin HEAD:main
